/** 与项目权限表同步：name 是路由权限名，code 是后端权限码。 */

export const PERMISSION_TABLE: Array<{ name: string; code: number; describe: string }> = [
  { name: '*', code: 1, describe: '所有权限' },
  { name: 'DataStatistics', code: 10, describe: '数据分析' },
  { name: 'Operation', code: 20, describe: '运营中心' },
  { name: 'Marketing', code: 30, describe: '营销管理' },
  { name: 'FinancialManage', code: 40, describe: '理财管理' },
  { name: 'Agent', code: 50, describe: '代理管理' },
  { name: 'Authorization', code: 60, describe: '权限管理' },
  { name: 'CustomerService', code: 70, describe: '客服配置' },
  { name: 'SystemConfig', code: 80, describe: '系统配置' },
  { name: 'Analysis', code: 1001, describe: '数据统计' },
  { name: 'ExchangeRateIndex', code: 1002, describe: '实时汇率监听' },
  { name: 'Announcement', code: 1003, describe: '现金池管理' },
  { name: 'UserStatisticsReport', code: 1004, describe: '增长统计报表' },
  { name: 'OrderTypeStatistics', code: 1005, describe: '订单类型统计' },
  { name: 'EnergyStatisticsReport', code: 1006, describe: '能量统计报表' },
  { name: 'SaleByTimeReport', code: 1007, describe: '按时间销售报表' },
  { name: 'PaymentStatisticsReport', code: 1008, describe: '支付统计报表' },
  { name: 'AgentMarketingAmount', code: 1009, describe: '代理营销额' },
  { name: 'RechargeOrder', code: 2001, describe: '充值订单' },
  { name: 'EnergyTransactionList', code: 2002, describe: '能量订单' },
  { name: 'FlashExchange', code: 2003, describe: '闪兑订单' },
  { name: 'CustodyDetails', code: 2004, describe: '托管列表' },
  { name: 'QuickChargeOrder', code: 2005, describe: '速充订单' },
  { name: 'AgentPrice', code: 3001, describe: '代理价格配置' },
  { name: 'AgentPrice.add', code: 3011, describe: '添加代理价格' },
  { name: 'AgentPrice.edit', code: 3012, describe: '编辑代理价格' },
  { name: 'AgentPrice.delete', code: 3013, describe: '删除代理价格' },
  { name: 'Payment', code: 3002, describe: '地址管理' },
  { name: 'Payment.add', code: 3021, describe: '添加收款地址' },
  { name: 'Payment.edit', code: 3022, describe: '编辑收款地址' },
  { name: 'Payment.delete', code: 3023, describe: '删除收款地址' },
  { name: 'WelfareConfig', code: 3003, describe: '福利配置' },
  { name: 'WelfareConfig.add', code: 3031, describe: '添加福利配置' },
  { name: 'WelfareConfig.edit', code: 3032, describe: '编辑福利配置' },
  { name: 'WelfareConfig.delete', code: 3033, describe: '删除福利配置' },
  { name: 'MarketingMenuList', code: 3004, describe: '菜单列表' },
  { name: 'MarketingMenuList.add', code: 3041, describe: '添加菜单' },
  { name: 'MarketingMenuList.edit', code: 3042, describe: '编辑菜单' },
  { name: 'MarketingMenuList.delete', code: 3043, describe: '删除菜单' },
  { name: 'MarketingGroupList', code: 3005, describe: '聊天列表' },
  { name: 'MarketingResourceDetail', code: 3006, describe: '资源详情' },
  { name: 'AddressBlacklist', code: 3007, describe: '地址黑名单' },
  { name: 'AddressBlacklist.add', code: 3071, describe: '添加地址黑名单' },
  { name: 'AddressBlacklist.edit', code: 3072, describe: '编辑地址黑名单' },
  { name: 'AddressBlacklist.delete', code: 3073, describe: '删除地址黑名单' },
  { name: 'MarketingReplyList', code: 3008, describe: '关键词回复' },
  { name: 'MarketingReplyList.add', code: 3081, describe: '添加关键词回复' },
  { name: 'MarketingReplyList.edit', code: 3082, describe: '编辑关键词回复' },
  { name: 'MarketingReplyList.delete', code: 3083, describe: '删除关键词回复' },
  { name: 'AdBannerConfig', code: 3009, describe: '广告横幅配置' },
  { name: 'AdBannerConfig.add', code: 3091, describe: '添加广告横幅' },
  { name: 'AdBannerConfig.edit', code: 3092, describe: '编辑广告横幅' },
  { name: 'AdBannerConfig.delete', code: 3093, describe: '删除广告横幅' },
  { name: 'FinancialPrice', code: 4001, describe: '理财价格配置' },
  { name: 'FinancialPrice.edit', code: 4011, describe: '编辑理财价格' },
  { name: 'ResourceOrder', code: 4002, describe: '理财订单列表' },
  { name: 'ResourceSupplementConfig', code: 4003, describe: '资源补充配置' },
  { name: 'ResourceSupplementConfig.add', code: 4031, describe: '添加资源补充' },
  { name: 'ResourceSupplementConfig.edit', code: 4032, describe: '编辑资源补充' },
  { name: 'ResourceSupplementOrder', code: 4004, describe: '资源补充记录' },
  { name: 'EnergyOutboundOrder', code: 4005, describe: '理财结算记录' },
  { name: 'ResourceAccountRechargeRecord', code: 4006, describe: '资源充值记录' },
  { name: 'OnChainInOutRecord', code: 4007, describe: '链上出入记录' },
  { name: 'AgentList', code: 5001, describe: '代理信息' },
  { name: 'AgentList.add', code: 5011, describe: '新增代理' },
  { name: 'AgentList.edit', code: 5012, describe: '编辑代理' },
  { name: 'AgentList.delete', code: 5013, describe: '删除代理' },
  { name: 'AgentLedger', code: 5002, describe: '代理账本' },
  { name: 'AgentBotList', code: 5003, describe: '机器人列表' },
  { name: 'AgentBotList.edit', code: 5031, describe: '编辑机器人' },
  { name: 'UserList', code: 5004, describe: '用户列表' },
  { name: 'AgentMessageList', code: 5005, describe: '消息列表' },
  { name: 'AgentMessageList.add', code: 5051, describe: '添加消息' },
  { name: 'AgentMessageList.edit', code: 5052, describe: '编辑消息' },
  { name: 'AgentMessageList.delete', code: 5053, describe: '删除消息' },
  { name: 'InviteList', code: 5006, describe: '邀请列表' },
  { name: 'UserBill', code: 5007, describe: '用户账单' },
  { name: 'AgentRechargeOrder', code: 5008, describe: '代理充值' },
  { name: 'User', code: 6001, describe: '用户管理' },
  { name: 'User.add', code: 6011, describe: '添加用户' },
  { name: 'User.edit', code: 6012, describe: '编辑用户' },
  { name: 'User.delete', code: 6013, describe: '删除用户' },
  { name: 'Role', code: 6002, describe: '角色管理' },
  { name: 'Role.add', code: 6021, describe: '添加角色' },
  { name: 'Role.edit', code: 6022, describe: '编辑角色' },
  { name: 'Role.delete', code: 6023, describe: '删除角色' },
  { name: 'CustomerServicePage', code: 7001, describe: '客服管理' },
  { name: 'CustomerServiceMessage', code: 7002, describe: '客服消息' },
  { name: 'ResourcePool', code: 8001, describe: '资源池账户' },
  { name: 'ResourcePool.add', code: 8011, describe: '创建资源池' },
  { name: 'ResourcePool.edit', code: 8012, describe: '编辑资源池' },
  { name: 'ResourcePool.delete', code: 8013, describe: '删除资源池' }
]

const nameByCode = new Map(PERMISSION_TABLE.map((item) => [String(item.code), item.name]))
const nameSet = new Set(PERMISSION_TABLE.map((item) => item.name))

export const toPermissionName = (value: string | number): string => {
  const raw = String(value).trim()
  if (!raw) return ''
  if (nameSet.has(raw)) return raw
  return nameByCode.get(raw) || raw
}

export const normalizePermissionNames = (values: Array<string | number> | null | undefined) => {
  if (!Array.isArray(values)) return []
  return [...new Set(values.map(toPermissionName).filter(Boolean))]
}
